name: chatbot
description: "AI Pharmbot - An AI-powered healthcare assistant app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
#
dependencies:
  flutter:
    sdk: flutter
    #
  cupertino_icons: ^1.0.8

  #
  #lottie animation
  lottie: ^3.3.1


  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
    #
  flutter_native_splash: ^2.4.6

 
  flutter_lints: ^5.0.0

  #
 
flutter:
#
  uses-material-design: true

  assets:
   - assets/images/logo.png 

   - assets/lottie/robo.json

  