name: chatbot
description: "AI Pharmbot - An AI-powered healthcare assistant app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
#
dependencies:
  flutter:
    sdk: flutter
    #
  cupertino_icons: ^1.0.8

  
  

  
  #lottie animation
  lottie: ^3.3.1

  #
  hive: ^2.2.3
  isar_flutter_libs: ^4.0.0-dev.13
  #
  path_provider: ^2.1.0

  #state mangement
  get: ^4.7.2


  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
    #
  flutter_native_splash: ^2.4.6

  #
  rename_app: ^1.6.5

  
 
  flutter_lints: 6.0.0

  #
 
flutter:
#
 uses-material-design: true

 assets:
    - assets/images/logo.png
    - assets/lottie/robo.json
    - assets/lottie/askme.json
    - assets/lottie/pharmAi.json
    - assets/lottie/ai_hand.json
    - assets/lottie/drugrem.json
    - assets/lottie/druginfo.json
    